### ISSUE TITLE
PMXs crashing Godot

### ISSUE THREAD

**Issue by LucasCTN** [V-Sekai/godot-pmx#12]
I'm very excited with this project, and wanted to test some PMXs I have laying around.
Unfortunately a bug is happening when loading some (not all) models.

For reference, I used [REM式初音ミクV4Xver1.1](https://bowlroll.net/file/130481).

To recreate:
* Compile Godot 4.0 and then the module inside Godot
* Create a new project
* Drag the folder with the .pmx to the project created
* Open the project on Godot

Godot starts to load the texture files. When the .pmx file starts being loaded, the window immediately closes.

The project will only work again if the folder with the .pmx is deleted.

**Comment by fire** [comment]
Will look into this. No promises though.

**Comment by fire** [comment]
I'll check this one.

**Comment by fire** [comment]
I will be uploading an update soon.

1. Bod.jpg -> bod.jpg
2. Eye.jpg -> eye.jpg
3. face.jpg -> FACE.jpg 
4. skinF.jpg -> skinf.jpg
5. Some names are case insensitive.

![image](https://user-images.githubusercontent.com/32321/185691311-1ed7fc06-b635-44ea-a3cc-7f9543379e51.png)

**Comment by LucasCTN** [comment]
Thank you so much!
